### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by DAddYE**
Hi,

thanks for all your effort in this driver.

I used it a little bit recently and I had to fix some issues.

Thanks!

### CODE REVIEW

**Comment by jpsilvashy** [comment]
@bpardee this looks great, want to merge this?

**Comment by bpardee** [comment]
Thanks @DAddYE.  Sorry, I've been out the past week so haven't had a chance to look at this.  We don't actually use this anymore so I'm curious if you would rather me merge or would you be interested in taking over maintenance of this gem?

**Comment by DAddYE** [comment]
@bpardee Hi. I'm using it extensively also at work where we have it in prod. So yes I'll be glad to maintain it. My personal email is `info[et]daddye.it`, I also use it on rubygems, feel free to add it or write me. Thanks, we truly appreciated your work!

**Comment by bpardee** [comment]
I've added you to rubygems so you should be able to push a version.  If successful, feel free to remove my email.

What would you prefer regarding github? I could transfer but I don't want to mess things up since you have an existing fork.

**Comment by DAddYE** [comment]
@bpardee thank you!!!!!!! 

You can merge, then transfer or simply add me to this repo, I'm fine with both, up to you! 

Again, super thanks!!!!!!!!!!!!!

**Comment by bpardee** [comment]
@DAddYE I've added you as a collaborator.  I attempted to transfer but since you already have a fork it failed.

**Comment by DAddYE** [comment]
Awesome, thanks! If you want re-attemp the transfer I deleted my repo! 

Thanks man!

**Comment by ianic** [comment]
I got truncated message published to nsq. The reason is difference between length and bytesize for multibyte strings. This is fixed in e9f4244f31cfb49413eb53705c372ff01b2e257b above.
Is there a chance to build a new gem with this fixes.

Thanks.

**Pull request merged**
